### ISSUE TITLE
Add slowpoke benchmark

### ISSUE THREAD

**Issue by recoilme** [dgraph-io/badger-bench#15]
slowpoke: https://github.com/recoilme/slowpoke
slowpoke very close to badger by design, but don't use LSMTree

**Comment by manishrjain** [comment]
Hey @recoilme ,

That's not a priority right now. Though, I really like what you've built, with the idea of key-value separation.

Will take a shot and ask if you'd like to help maintain and improve Badger. Your strengths can be valuable to the project.

Cheers,
Manish

**Comment by recoilme** [comment]
@manishrjain Thank dgraph team for the beautiful idea about key separation! You do the very good job
Cheers,
Vadim
