### ISSUE TITLE
Trouble running tests in Ubuntu Docker container

### ISSUE THREAD

**Issue by lsimmons2** [dgraph-io/badger-bench#18]
Hi all, I'm trying to run the tests in an ubuntu docker container and am having some trouble. After following the steps in the **Setting Up Instance** section of [the README](https://github.com/dgraph-io/badger-bench/blob/master/BENCH-lmdb-bolt.md), I'm unable to 1) run `go test --bench BenchmarkLmdbBatch` and 2) run `populate --kv lmdb`.

1) Running `go test --bench BenchmarkLmdbBatch`

Running `go test --bench BenchmarkLmdbBatch --dir /mnt/data --benchtime 30s` from `badger-bench/populate` as shown in the README I get:

    ?   	github.com/dgraph-io/badger-bench/populate	[no test files]

Running the same command from `badger-bench/` I get:

    PASS
    ok  	github.com/dgraph-io/badger-bench	0.027s

2) Running `populate --kv lmdb`

Running `populate --kv lmdb --valsz 16384 --keys_mil 5 --dir /mnt/data/16kb` (after building `populate` command) I get:

    TOTAL KEYS TO WRITE:   5.00M
    2019/09/11 21:04:06 Invalid value for option kv: 'lmdb'

Steps to reproduce environment:
1) start docker container `docker run -it ubuntu:xenial`
2) run the following script (either with `Dockerfile` or after using `docker cp`) - this script combines the steps in the **Setting Up Instance** section of [the README](https://github.com/dgraph-io/badger-bench/blob/master/BENCH-lmdb-bolt.md) except for the formatting/mounting of the SSD volume.

```
#!/bin/bash
echo "INSTALLING SYSTEM DEPENDENCIES"
apt-get update -y
apt-get install -y wget build-essential git libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev sysstat fio
echo "export GOMAXPROCS=128" >> ~/.bashrc

echo "CREATE DROP_CACHES SCRIPT"
touch ~/drop_caches.sh
chmod +x ~/drop_caches.sh
echo "#!/bin/sh" >> ~/drop_caches.sh
echo "echo 3 | tee /proc/sys/vm/drop_caches" >> ~/drop_caches.sh
echo "blockdev --flushbufs /dev/nvme0n1" >> ~/drop_caches.sh

echo "INSTALL ROCKSDB"
wget https://github.com/facebook/rocksdb/archive/v5.1.4.tar.gz
tar -xzvf v5.1.4.tar.gz
cd rocksdb-5.1.4
make shared_lib -d && make install-shared -d
ldconfig

echo "INSTALLING GOLANG"
cd
wget https://storage.googleapis.com/golang/go1.9.linux-amd64.tar.gz # need 1.9 for math/bits
tar -xvf go1.9.linux-amd64.tar.gz
mv go /usr/local/
export PATH=$PATH:/usr/local/go/bin
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

echo "INSTALLING BADGER-BENCH REPO"
go get -t -v github.com/dgraph-io/badger-bench/...
cd $GOPATH/src/github.com/dgraph-io/badger-bench
go test


echo "BUILDING BADGER-BENCH COMMANDS"
cd populate
go install
```

**Comment by danielmai** [comment]
We removed the benchmark tests with lmdb (https://github.com/dgraph-io/badger-bench/commit/57131aa35453997de5175f3c47237dfc4eb0bfd2) and removed the benchmark test `BenchmarkLmdbBatch` (7f173efefb843854056a50ba2cd4bbff1466de94) quite some time ago.

You can try reverting back in the commit history and try to run the tests. But there's no guarantee that they'll work as-is, though.

**Comment by danielmai** [comment]
@lsimmons2 #18 brought back the LMDB benchmarks into master, so you should be able to run both `go test --bench BenchmarkLmdbBatch` and `populate --kv lmdb` now.
