### ISSUE TITLE
Can't run benchmarks due to missing package

### ISSUE THREAD

**Issue by adirg** [dgraph-io/badger-bench#2]
Hi,

I'm trying to run the benchmarks described in BENCH.md (i.e. `go test --bench BenchmarkReadRandomRocks --keys_mil 250 --valsz 128 --dir "/mnt/data" --timeout 10m --benchtime 3m`), but unfortunately I get the following error: 
```
# github.com/dgraph-io/badger-bench
bench_test.go:15:2: cannot find package "github.com/dgraph-io/dgraph/store" in any of:
        /usr/local/go/src/github.com/dgraph-io/dgraph/store (from $GOROOT)
        /home/adir/gowork/src/github.com/dgraph-io/dgraph/store (from $GOPATH)
FAIL    github.com/dgraph-io/badger-bench [setup failed]
```

When searching through the dgraph repo, I can't find any store package.
I'm using master branch in badger, badger-bench and dgraph repositories.

What am I missing here?

Thanks,
Adir

**Comment by adirg** [comment]
OK, I found out that the store package got deleted in ed048d5d59248875c55ff5fbf14025e67f1a164c (as part of the move from rockdb to badger).

Does it mean that the rocksdb benchmarks are not supported anymore?

**Comment by manishrjain** [comment]
Someone will have to integrate go RocksDB back to this. Possibly copying it over from what Dgraph had before.

**Comment by ashwin95r** [comment]
RocksDB has been brought back in this repo (`store` and `rdb`).
